### ISSUE TITLE
Authomatic install failing

### ISSUE THREAD

**Issue by rdmurphy** [nprapps/watermarker#12]
Here's the error I get when I try to `pip install -r requirements.txt`:

``` sh
Obtaining Authomatic from git+git@github.com:peterhudec/authomatic.git@70c740546d9849271e35edbf3da30e1801f7a227#egg=Authomatic (from -r requirements.txt (line 1))
  Cloning git@github.com:peterhudec/authomatic.git (to 70c740546d9849271e35edbf3da30e1801f7a227) to /Users/ryan/.virtualenvs/waterbug-dev/src/authomatic
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
  Complete output from command git clone -q git@github.com:peterhudec/authomatic.git /Users/ryan/.virtualenvs/waterbug-dev/src/authomatic:

  ----------------------------------------
  Command "git clone -q git@github.com:peterhudec/authomatic.git /Users/ryan/.virtualenvs/waterbug-dev/src/authomatic" failed with error code 128 in None
```

**Comment by rdmurphy** [comment]
[Guessing the commit isn't available anymore](https://github.com/peterhudec/authomatic.git@70c740546d9849271e35edbf3da30e1801f7a227)!

**Comment by eads** [comment]
Did bumping the version in reqs fix things for you?

On Thu, Apr 30, 2015 at 12:04 PM, Ryan Murphy notifications@github.com
wrote:

> Guessing the commit isn't available anymore
> https://github.com/peterhudec/authomatic.git@70c740546d9849271e35edbf3da30e1801f7a227
> !
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nprapps/waterbug/issues/12#issuecomment-97854212.

## 

David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by rdmurphy** [comment]
Yup – authomatic was all happy after that pull. Thanks!
