### ISSUE TITLE
In need of protips 

### ISSUE THREAD

**Issue by bcoffing** [nprapps/watermarker#13]
What if we don't know what any of this means and/or we don't post photo creds? Asking for a friend.

**Comment by dannydb** [comment]
@bcoffing take, for instance, your photos posted to the [straightupselfies](https://instagram.com/straightupselfies/) Instagram account. You probably want to share those images with your twitter followers, but once you’ve tweeted said image, it can be taken and reposted with zero indication that the photo is in fact a selfie made by you. Waterbug ensures the credit for the image is portable across any Twitter reuse…

![](http://dbeli.us/m8Mx+)

Hope that helps. Closing the ticket, but open a new one if you have further questions or concerns.

**Comment by bcoffing** [comment]
Thank you for the prompt assistance. The furthering of my brand will be maximized by your simple tool.
